/*
 * THIS FILE WAS GENERATED BY PLOTLY.BLAZOR.GENERATOR
*/

using System;
using System.Text.Json.Serialization;
using System.Runtime.Serialization;

namespace Plotly.Blazor.ConfigLib
{
    /// <summary>
    ///     Determines whether mouse wheel or two-finger scroll zooms is enable. Turned
    ///     on by default for gl3d, geo and mapbox subplots (as these subplot types
    ///     do not have zoombox via pan), but turned off by default for cartesian subplots.
    ///     Set `scrollZoom` to *false* to disable scrolling for all subplots.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Plotly.Blazor.Generator", "1.0.0.0")]
    [Flags]
    [JsonConverter(typeof(EnumConverter))]
    public enum ScrollZoomFlag
    {
        [EnumMember(Value=@"True")]
        True = 0,
        [EnumMember(Value=@"False")]
        False = 1,
        [EnumMember(Value=@"cartesian")]
        Cartesian = 2,
        [EnumMember(Value=@"gl3d")]
        Gl3D = 4,
        [EnumMember(Value=@"geo")]
        Geo = 8,
        [EnumMember(Value=@"mapbox")]
        MapBox = 16
    }
}