/*
 * THIS FILE WAS GENERATED BY PLOTLY.BLAZOR.GENERATOR
*/

using System.Text.Json.Serialization;

namespace Plotly.Blazor.LayoutLib.GeoLib
{
    /// <summary>
    ///     The Center class.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Plotly.Blazor.Generator", "1.0.0.0")]
    public class Center 
    {
        /// <summary>
        ///     Sets the longitude of the map&#39;s center. By default, the map&#39;s longitude
        ///     center lies at the middle of the longitude range for scoped projection and
        ///     above <c>projection.rotation.lon</c> otherwise.
        /// </summary>
        [JsonPropertyName(@"lon")]
        public float? Lon { get; set;} 

        /// <summary>
        ///     Sets the latitude of the map&#39;s center. For all projection types, the
        ///     map&#39;s latitude center lies at the middle of the latitude range by default.
        /// </summary>
        [JsonPropertyName(@"lat")]
        public float? Lat { get; set;} 

    }
}