/*
 * THIS FILE WAS GENERATED BY PLOTLY.BLAZOR.GENERATOR
*/

using System;
using System.Text.Json.Serialization;
using System.Runtime.Serialization;
#pragma warning disable 1591

namespace Plotly.Blazor.Traces.TreeMapLib
{
    /// <summary>
    ///     Determines which trace information appear on the graph.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Plotly.Blazor.Generator", "1.0.0.0")]
    [Flags]
    [JsonConverter(typeof(EnumConverter))]
    public enum TextInfoFlag
    {
        [EnumMember(Value=@"none")]
        None = 0,
        [EnumMember(Value=@"label")]
        Label = 1,
        [EnumMember(Value=@"text")]
        Text = 2,
        [EnumMember(Value=@"value")]
        Value = 4,
        [EnumMember(Value=@"current path")]
        CurrentPath = 8,
        [EnumMember(Value=@"percent root")]
        PercentRoot = 16,
        [EnumMember(Value=@"percent entry")]
        PercentEntry = 32,
        [EnumMember(Value=@"percent parent")]
        PercentParent = 64
    }
}