/*
 * THIS FILE WAS GENERATED BY PLOTLY.BLAZOR.GENERATOR
*/

using System.Text.Json.Serialization;
using System.Collections.Generic;

namespace Plotly.Blazor.Traces.IndicatorLib.DeltaLib
{
    /// <summary>
    ///     The Decreasing class.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Plotly.Blazor.Generator", "1.0.0.0")]
    public class Decreasing 
    {
        /// <summary>
        ///     Sets the symbol to display for increasing value
        /// </summary>
        [JsonPropertyName(@"symbol")]
        public string Symbol { get; set;} 

        /// <summary>
        ///     Sets the color for increasing value.
        /// </summary>
        [JsonPropertyName(@"color")]
        public object Color { get; set;} 

    }
}