/*
 * THIS FILE WAS GENERATED BY PLOTLY.BLAZOR.GENERATOR
*/

using System.Text.Json.Serialization;
using System.Runtime.Serialization;
#pragma warning disable 1591

namespace Plotly.Blazor.LayoutLib.LegendLib
{
    /// <summary>
    ///     Determines the behavior on legend title double-click. <c>toggle</c> toggles
    ///     the visibility of all items in the legend. <c>toggleothers</c> toggles the
    ///     visibility of all other legends. <c>false</c> disables legend title double-click
    ///     interactions. Defaults to <c>toggleothers</c> when there are multiple legends,
    ///     <c>false</c> otherwise. Not supported for legends containing pie and pie-like
    ///     traces.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Plotly.Blazor.Generator", null)]
    [JsonConverter(typeof(EnumConverter))]
    public enum TitleDoubleClickEnum
    {
        [EnumMember(Value=@"toggle")]
        Toggle,
        [EnumMember(Value=@"toggleothers")]
        ToggleOthers,
        [EnumMember(Value=@"False")]
        False
    }
}