/*
 * THIS FILE WAS GENERATED BY PLOTLY.BLAZOR.GENERATOR
*/

using System.Text.Json.Serialization;
using System.Runtime.Serialization;
#pragma warning disable 1591

namespace Plotly.Blazor.LayoutLib.PolarLib.AngularAxisLib
{
    /// <summary>
    ///     Sets the format unit of the formatted <c>theta</c> values. Has an effect
    ///     only when <c>angularaxis.type</c> is <c>linear</c>.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Plotly.Blazor.Generator", "1.0.0.0")]
    [JsonConverter(typeof(EnumConverter))]
    public enum ThetaUnitEnum
    {
        [EnumMember(Value=@"degrees")]
        Degrees = 0,
        [EnumMember(Value=@"radians")]
        Radians
    }
}