/*
 * THIS FILE WAS GENERATED BY PLOTLY.BLAZOR.GENERATOR
*/

using System.Text.Json.Serialization;
using System.Runtime.Serialization;

namespace Plotly.Blazor.Traces.BarLib
{
    /// <summary>
    ///     Specifies the location of the `text`. *inside* positions `text` inside,
    ///     next to the bar end (rotated and scaled if needed). *outside* positions
    ///     `text` outside, next to the bar end (scaled if needed), unless there is
    ///     another bar stacked on this one, then the text gets pushed inside. *auto*
    ///     tries to position `text` inside the bar, but if the bar is too small and
    ///     no bar is stacked on this one the text is moved outside.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Plotly.Blazor.Generator", "1.0.0.0")]
    [JsonConverter(typeof(EnumConverter))]
    public enum TextPositionEnum
    {
        [EnumMember(Value=@"none")]
        None = 0,
        [EnumMember(Value=@"inside")]
        Inside,
        [EnumMember(Value=@"outside")]
        Outside,
        [EnumMember(Value=@"auto")]
        Auto
    }
}