/*
 * THIS FILE WAS GENERATED BY PLOTLY.BLAZOR.GENERATOR
*/

using System.Text.Json.Serialization;
using System.Runtime.Serialization;

namespace Plotly.Blazor.LayoutLib.GridLib
{
    /// <summary>
    ///     If no `subplots`, `xaxes`, or `yaxes` are given but we do have `rows` and
    ///     `columns`, we can generate defaults using consecutive axis IDs, in two ways:
    ///     *coupled* gives one x axis per column and one y axis per row. *independent*
    ///     uses a new xy pair for each cell, left-to-right across each row then iterating
    ///     rows according to `roworder`.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Plotly.Blazor.Generator", "1.0.0.0")]
    [JsonConverter(typeof(EnumConverter))]
    public enum PatternEnum
    {
        [EnumMember(Value=@"coupled")]
        Coupled = 0,
        [EnumMember(Value=@"independent")]
        Independent
    }
}