/*
 * THIS FILE WAS GENERATED BY PLOTLY.BLAZOR.GENERATOR
*/

using System.Text.Json.Serialization;
using System.Collections.Generic;
using Plotly.Blazor.LayoutLib.SliderLib.CurrentValueLib;

namespace Plotly.Blazor.LayoutLib.SliderLib
{
    /// <summary>
    ///     The CurrentValue class.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Plotly.Blazor.Generator", "1.0.0.0")]
    public class CurrentValue 
    {
        /// <summary>
        ///     Shows the currently-selected value above the slider.
        /// </summary>
        [JsonPropertyName(@"visible")]
        public bool? Visible { get; set;} 

        /// <summary>
        ///     The alignment of the value readout relative to the length of the slider.
        /// </summary>
        [JsonPropertyName(@"xanchor")]
        public Plotly.Blazor.LayoutLib.SliderLib.CurrentValueLib.XAnchorEnum? XAnchor { get; set;} 

        /// <summary>
        ///     The amount of space, in pixels, between the current value label and the
        ///     slider.
        /// </summary>
        [JsonPropertyName(@"offset")]
        public float? Offset { get; set;} 

        /// <summary>
        ///     When currentvalue.visible is true, this sets the prefix of the label.
        /// </summary>
        [JsonPropertyName(@"prefix")]
        public string Prefix { get; set;} 

        /// <summary>
        ///     When currentvalue.visible is true, this sets the suffix of the label.
        /// </summary>
        [JsonPropertyName(@"suffix")]
        public string Suffix { get; set;} 

        /// <summary>
        ///     Sets the font of the current value label text.
        /// </summary>
        [JsonPropertyName(@"font")]
        public Plotly.Blazor.LayoutLib.SliderLib.CurrentValueLib.Font Font { get; set;} 

    }
}