/*
 * THIS FILE WAS GENERATED BY PLOTLY.BLAZOR.GENERATOR
*/

using System.Text.Json.Serialization;
using System.Collections.Generic;

namespace Plotly.Blazor.LayoutLib.MapBoxLib.LayerLib
{
    /// <summary>
    ///     The Fill class.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Plotly.Blazor.Generator", "1.0.0.0")]
    public class Fill 
    {
        /// <summary>
        ///     Sets the fill outline color (mapbox.layer.paint.fill-outline-color). Has
        ///     an effect only when `type` is set to *fill*.
        /// </summary>
        [JsonPropertyName(@"outlinecolor")]
        public object OutlineColor { get; set;} 

    }
}