/*
 * THIS FILE WAS GENERATED BY PLOTLY.BLAZOR.GENERATOR
*/

using System.Text.Json.Serialization;
using System.Collections.Generic;

namespace Plotly.Blazor.LayoutLib.MapBoxLib.LayerLib
{
    /// <summary>
    ///     The Line class.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Plotly.Blazor.Generator", "1.0.0.0")]
    public class Line 
    {
        /// <summary>
        ///     Sets the line width (mapbox.layer.paint.line-width). Has an effect only
        ///     when `type` is set to *line*.
        /// </summary>
        [JsonPropertyName(@"width")]
        public float? Width { get; set;} 

        /// <summary>
        ///     Sets the length of dashes and gaps (mapbox.layer.paint.line-dasharray).
        ///     Has an effect only when `type` is set to *line*.
        /// </summary>
        [JsonPropertyName(@"dash")]
        public IList<object> Dash { get; set;} 

        /// <summary>
        ///     Sets the source reference on Chart Studio Cloud for  dash .
        /// </summary>
        [JsonPropertyName(@"dashsrc")]
        public string DashSrc { get; set;} 

    }
}