name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main # Default release branch
      - develop
      - 'releases/**'
    paths:
      - 'Plotly.Blazor/**' 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: | 
          6.0.x
          7.0.x
          8.0.x
          9.0.x
    - name: Build with .NET
      run: dotnet build --configuration Release
    - name: Test with .NET
      run: dotnet test
